import { Novel, NovelGenre, NovelStatus, WeeklyData } from "@/types/novel_type";

export const genres: (NovelGenre | "All")[] = [
  "Fantasy",
  "Romance",
  "Mystery",
  "Adventure",
  "Sci-Fi",
  "Drama",
  "Thriller",
  "Action",
  "Comedy",
  "Horror",
  "Mecha",
  "Slice of Life",
  "Eastern",
  "Games",
];

export const statuses: (NovelStatus | "All")[] = [
  "All",
  "Ongoing",
  "Completed",
  "Hiatus",
];

export const novels: Novel[] = [
  {
    id: 1,
    title: "Moonlit Dreams",
    author: "Luna West",
    cover: "/novels/hero-section/novel_1.png",
    rating: 4.8,
    votes: 2412,
    chapters: 156,
    views: 2.4,
    genre: "Fantasy",
    status: "Ongoing",
    tags: ["Magic", "Kingdom", "Dreams"],
    description:
      "In a world where dreams hold magical power, a young woman discovers she can enter the dreams of others and must use this ability to save her kingdom from a dark force.",
    longDescription:
      "As the lines between dreams and reality blur, Luna must face not only the monsters that haunt her sleep but also the dark truths that threaten to unravel her world.",
  },
  {
    id: 2,
    title: "Ethereal Chronicles",
    author: "Aria Moon",
    cover: "/novels/hero-section/novel_2.png",
    rating: 4.6,
    votes: 3100,
    chapters: 203,
    views: 3.1,
    genre: "Adventure",
    status: "Ongoing",
    tags: ["Epic", "Adventure", "Magic"],
    description:
      "A young adventurer embarks on a quest to find the legendary Ethereal Chronicles, a book said to hold the power to control the elements and save the world from destruction.",
    longDescription:
      "With the fate of the world hanging in the balance, Aria must navigate treacherous lands and forge alliances to unlock the secrets of the Ethereal Chronicles and restore harmony to the elements.",
  },
  {
    id: 3,
    title: "The Whispering Stars",
    author: "Alyssa K. Moran",
    cover: "/novels/hero-section/novel_1.png",
    rating: 4.8,
    votes: 3100,
    chapters: 203,
    views: 3.1,
    genre: "Adventure",
    status: "Ongoing",
    tags: ["Epic", "Adventure", "Magic"],
    description:
      "In a tranquil kingdom where the stars are believed to be silent watchers of fate, young astronomer Elara discovers she can hear their whispers — faint voices echoing through her telescope. As she learns to interpret their celestial language, the constellations reveal ominous prophecies of a coming darkness that threatens to swallow her world. Torn between loyalty to her king and the cosmic truths written in the heavens, Elara must choose whether to warn her people or risk being branded a heretic in a realm that no longer believes in magic.",
    longDescription:
      "Elara's journey takes her from the quiet observatory to the heart of a cosmic battle, where she must confront not only the dark forces threatening her world but also the personal demons that haunt her past.",
  },
  {
    id: 4,
    title: "Chronicles of Emberfall",
    author: "Darius Vale",
    cover: "/novels/hero-section/novel_2.png",
    rating: 4.6,
    votes: 8450,
    chapters: 95,
    views: 84.5,
    genre: "Fantasy",
    status: "Ongoing",
    tags: ["Fantasy", "Rebellion", "Magic"],
    description:
      "In a world where magic is forbidden, a group of rebels fights to restore the ancient magic and overthrow the tyrannical king.",
    longDescription:
      "As the rebels gain strength, they uncover ancient secrets and forge alliances that could turn the tide of the rebellion and restore magic to the world.",
  },
  {
    id: 5,
    title: "The Silver Sonata",
    author: "Clara Noveen",
    cover: "/novels/hero-section/novel_3.png",
    rating: 4.9,
    votes: 9920,
    chapters: 78,
    views: 99.2,
    genre: "Drama",
    status: "Completed",
    tags: ["Drama", "Romance", "Music"],
    description:
      "A young musician discovers a magical instrument that can bring her lost love back to life, but at a terrible cost.",
    longDescription:
      "As Clara delves deeper into the mysteries of the magical instrument, she must confront the consequences of her actions and decide whether the love she seeks is worth the price she must pay.",
  },
  {
    id: 6,
    title: "Garden of Forgotten Dreams",
    author: "Ren Saito",
    cover: "/novels/hero-section/novel_4.png",
    rating: 4.7,
    votes: 6780,
    chapters: 65,
    views: 67.8,
    genre: "Fantasy",
    status: "Ongoing",
    tags: ["Fantasy", "Mystery", "Dreams"],
    description:
      "A young dreamwalker enters the dreams of others to solve a series of mysterious murders, but soon realizes that the dreams are more dangerous than reality.",
    longDescription:
      "As the dreamwalker delves deeper into the dreams, they uncover a web of deceit and danger that threatens not only their own life but the very fabric of reality.",
  },
  {
    id: 7,
    title: "The Last Eclipse",
    author: "Mira Solen",
    cover: "/novels/hero-section/novel_5.png",
    rating: 4.9,
    votes: 11020,
    chapters: 102,
    views: 110.2,
    genre: "Adventure",
    status: "Ongoing",
    tags: ["Adventure", "Fantasy", "Myth"],
    description:
      "A young adventurer embarks on a quest to find the legendary Last Eclipse, a mythical event said to grant one wish to whoever witnesses it.",
    longDescription:
      "As the adventurer journeys through treacherous lands and faces mythical creatures, they must unravel the secrets of the Last Eclipse and decide what wish they will make when the time comes.",
  },
  {
    id: 8,
    title: "Reincarnated As A Lion In Another World",
    author: "Haru Kenzaki",
    cover: "/novels/weekly/reincarnated_lion.jpg",
    rating: 4.8,
    votes: 13460,
    chapters: 210,
    views: 134.6,
    genre: "Fantasy",
    status: "Ongoing",
    tags: ["Fantasy", "Reincarnation", "Beast"],
    description:
      "After dying in a traffic accident, a young man awakens as a lion cub in a world filled with magic and monsters. To survive, he must evolve through the food chain — and uncover why the gods chose him for this savage rebirth.",
    longDescription:
      "As the lion cub grows and evolves, he must navigate the dangerous world of magic and monsters, forging alliances and uncovering the truth behind his reincarnation.",
  },
  {
    id: 9,
    title: "Forced to Be a Villain",
    author: "Jin Wuyue",
    cover: "/novels/weekly/villain.jpg",
    rating: 4.7,
    votes: 12130,
    chapters: 188,
    views: 121.3,
    genre: "Eastern",
    status: "Ongoing",
    tags: ["Eastern", "Action", "Revenge"],
    description:
      "After being betrayed by his sect and branded a villain, Lin Feng decides to embrace his dark destiny — only to realize that every villain hides a deeper truth the heroes dare not face.",
    longDescription:
      "As Lin Feng delves deeper into his dark destiny, he uncovers the true nature of the heroes and the secrets they hide, forcing him to question his own path.",
  },
  {
    id: 10,
    title: "Rivers of the Night",
    author: "Li Chengyan",
    cover: "/novels/weekly/rivers_night.jpg",
    rating: 4.6,
    votes: 9840,
    chapters: 165,
    views: 98.4,
    genre: "Eastern",
    status: "Completed",
    tags: ["Eastern", "Martial Arts", "Dark"],
    description:
      "A lone cultivator wanders through a world of eternal twilight, where every river carries the memories of the dead. To reclaim his soul, he must conquer the flow of darkness itself.",
    longDescription:
      "As the cultivator journeys through the world of eternal twilight, he must confront the memories of the dead and the darkness that threatens to consume him.",
  },
  {
    id: 11,
    title: "Floating Islands: SSS",
    author: "Eira Wren",
    cover: "/novels/weekly/floating_islands.jpg",
    rating: 4.9,
    votes: 15070,
    chapters: 143,
    views: 150.7,
    genre: "Fantasy",
    status: "Ongoing",
    tags: ["Fantasy", "Adventure", "World-Building"],
    description:
      "In a world of floating continents drifting above a storm-torn sea, a young explorer earns the rare SSS rank and discovers a secret that could unite or destroy the skies themselves.",
    longDescription:
      "As the explorer delves deeper into the secrets of the floating islands, they must navigate the treacherous politics and alliances that threaten to tear the skies apart.",
  },
  {
    id: 12,
    title: "Strongest Necromancer System",
    author: "Damon Arctis",
    cover: "/novels/weekly/necromancer.jpg",
    rating: 4.8,
    votes: 17540,
    chapters: 230,
    views: 175.4,
    genre: "Fantasy",
    status: "Ongoing",
    tags: ["Fantasy", "System", "Necromancy"],
    description:
      "After being betrayed by his party, a dying mage forms a pact with the God of Death — awakening a system that grants power through souls. Every kill brings strength… but also madness.",
    longDescription:
      "As the necromancer gains power through the souls of the dead, he must confront the madness that threatens to consume him and the consequences of his actions.",
  },
  {
    id: 13,
    title: "Werewolf Leveling in the Apocalypse",
    author: "Kai Draven",
    cover: "/novels/weekly/werewolf.jpg",
    rating: 4.7,
    votes: 14290,
    chapters: 156,
    views: 142.9,
    genre: "Fantasy",
    status: "Ongoing",
    tags: ["Fantasy", "Apocalypse", "Werewolf"],
    description:
      "When an apocalyptic virus turns humans into monsters, Ethan is bitten by a werewolf — but instead of dying, he awakens with a leveling system tied to the moon’s phases.",
    longDescription:
      "As Ethan navigates the dangerous world of the apocalypse, he must level up and forge alliances to survive and uncover the truth behind the virus.",
  },
  {
    id: 14,
    title: "Online Game: Low Level Hero",
    author: "Rin Okada",
    cover: "/novels/weekly/online_game.jpg",
    rating: 4.5,
    votes: 8820,
    chapters: 120,
    views: 88.2,
    genre: "Games",
    status: "Ongoing",
    tags: ["Games", "Action", "VRMMO"],
    description:
      "In a hyper-realistic VRMMO, players chase glory and power — but one low-level player discovers a secret bug that lets him rewrite the system itself.",
    longDescription:
      "As the low-level player delves deeper into the secrets of the VRMMO, he must navigate the treacherous world of online gaming and the consequences of his actions.",
  },
  {
    id: 15,
    title: "Goblin Dependency",
    author: "Nero Falx",
    cover: "/novels/weekly/goblin_dependency.jpg",
    rating: 4.4,
    votes: 7650,
    chapters: 97,
    views: 76.5,
    genre: "Fantasy",
    status: "Ongoing",
    tags: ["Fantasy", "Dark", "Goblin"],
    description:
      "A disgraced alchemist creates a potion to control goblins — but when the tables turn, he becomes addicted to the very creatures he sought to enslave.",
    longDescription:
      "As the alchemist delves deeper into his addiction, he must confront the dark consequences of his actions and the true nature of the goblins he sought to control.",
  },
  {
    id: 16,
    title: "Echoes of Eternity",
    author: "Luna Virelle",
    cover: "/novels/rankings/overall_1.png",
    rating: 4.9,
    votes: 15050,
    chapters: 120,
    views: 150.5,
    genre: "Fantasy",
    status: "Ongoing",
    tags: ["Fantasy", "Adventure", "Myth"],
    description:
      "In a world where time is a currency, a young mage must unravel the secrets of eternal life to save her kingdom from a dark force.",
    longDescription:
      "As the mage delves deeper into the secrets of eternal life, she must navigate the treacherous world of time and the dark forces that threaten her kingdom.",
  },
  {
    id: 17,
    title: "Code of Shadows",
    author: "Rei Nakamura",
    cover: "/novels/rankings/overall_2.png",
    rating: 4.8,
    votes: 13030,
    chapters: 95,
    views: 130.3,
    genre: "Thriller",
    status: "Ongoing",
    tags: ["Thriller", "Mystery", "Action"],
    description:
      "A former assassin turned detective must solve a series of murders that hint at a conspiracy within the city's elite.",
    longDescription:
      "As the detective delves deeper into the conspiracy, he must navigate the treacherous world of the city's elite and the dark secrets they hide.",
  },
  {
    id: 18,
    title: "The Whispering Stars",
    author: "Alyssa K. Moran",
    cover: "/novels/rankings/overall_3.png",
    rating: 4.8,
    votes: 14020,
    chapters: 110,
    views: 140.2,
    genre: "Fantasy",
    status: "Ongoing",
    tags: ["Fantasy", "Romance", "Adventure"],
    description:
      "A princess with the power to communicate with stars embarks on a journey to find her missing brother and uncover the truth about her kingdom's past.",
    longDescription:
      "As the princess delves deeper into the mysteries of her kingdom's past, she must navigate the treacherous world of court politics and the dark secrets that threaten her family.",
  },
  {
    id: 19,
    title: "Empire of Ashes",
    author: "Darius Vale",
    cover: "/novels/rankings/overall_4.png",
    rating: 4.7,
    votes: 12010,
    chapters: 85,
    views: 120.1,
    genre: "Action",
    status: "Ongoing",
    tags: ["Action", "Adventure", "Fantasy"],
    description:
      "A group of rebels fights against an oppressive empire in a world where magic and technology coexist.",
    longDescription:
      "As the rebels gain strength, they must navigate the treacherous world of magic and technology and the dark secrets that threaten their rebellion.",
  },
  {
    id: 20,
    title: "The Silent Crown",
    author: "Ren Saito",
    cover: "/novels/rankings/overall_5.png",
    rating: 4.6,
    votes: 10000,
    chapters: 70,
    views: 100.0,
    genre: "Drama",
    status: "Ongoing",
    tags: ["Drama", "Romance", "Mystery"],
    description:
      "A young queen must navigate the treacherous waters of court politics and romance while trying to protect her kingdom from internal and external threats.",
    longDescription:
      "As the queen delves deeper into the mysteries of her kingdom, she must navigate the treacherous world of court politics and the dark secrets that threaten her rule.",
  },
  {
    id: 21,
    title: "Garden of Forgotten Dreams",
    author: "Ren Saito",
    cover: "/novels/rankings/fantasy_1.png",
    rating: 4.9,
    votes: 15050,
    chapters: 120,
    views: 150.5,
    genre: "Fantasy",
    status: "Ongoing",
    tags: ["Fantasy", "Adventure", "Myth"],
    description:
      "In a world where time is a currency, a young mage must unravel the secrets of eternal life to save her kingdom from a dark force.",
    longDescription:
      "As the mage delves deeper into the secrets of eternal life, she must navigate the treacherous world of time and the dark forces that threaten her kingdom.",
  },
  {
    id: 22,
    title: "Chronicles of Emberfall",
    author: "Darius Vale",
    cover: "/novels/rankings/fantasy_2.png",
    rating: 4.8,
    votes: 13030,
    chapters: 95,
    views: 130.3,
    genre: "Fantasy",
    status: "Ongoing",
    tags: ["Fantasy", "Adventure", "Myth"],
    description:
      "A former assassin turned detective must solve a series of murders that hint at a conspiracy within the city's elite.",
    longDescription:
      "As the detective delves deeper into the conspiracy, he must navigate the treacherous world of the city's elite and the dark secrets they hide.",
  },
  {
    id: 23,
    title: "The Last Eclipse",
    author: "Mira Solen",
    cover: "/novels/rankings/fantasy_3.png",
    rating: 4.8,
    votes: 14020,
    chapters: 110,
    views: 140.2,
    genre: "Fantasy",
    status: "Ongoing",
    tags: ["Fantasy", "Romance", "Adventure"],
    description:
      "A princess with the power to communicate with stars embarks on a journey to find her missing brother and uncover the truth about her kingdom's past.",
    longDescription:
      "As the princess delves deeper into the mysteries of her kingdom's past, she must navigate the treacherous world of court politics and the dark secrets that threaten her family.",
  },
  {
    id: 24,
    title: "The Silver Sonata",
    author: "Clara Noveen",
    cover: "/novels/rankings/fantasy_4.png",
    rating: 4.7,
    votes: 12010,
    chapters: 85,
    views: 120.1,
    genre: "Fantasy",
    status: "Ongoing",
    tags: ["Fantasy", "Action", "Adventure"],
    description:
      "A group of rebels fights against an oppressive empire in a world where magic and technology coexist.",
    longDescription:
      "As the rebels gain strength, they must navigate the treacherous world of magic and technology and the dark secrets that threaten their rebellion.",
  },
  {
    id: 25,
    title: "The Whispering Stars",
    author: "Alyssa K. Moran",
    cover: "/novels/rankings/fantasy_5.png",
    rating: 4.7,
    votes: 10000,
    chapters: 70,
    views: 100.0,
    genre: "Fantasy",
    status: "Ongoing",
    tags: ["Fantasy", "Drama", "Romance"],
    description:
      "A young queen must navigate the treacherous waters of court politics and romance while trying to protect her kingdom from internal and external threats.",
    longDescription:
      "As the queen delves deeper into the mysteries of her kingdom, she must navigate the treacherous world of court politics and the dark secrets that threaten her rule.",
  },
  {
    id: 26,
    title: "The Blossoming Veil",
    author: "Elara Mistral",
    cover: "/novels/rankings/romance_1.png",
    rating: 4.9,
    votes: 15050,
    chapters: 120,
    views: 150.5,
    genre: "Romance",
    status: "Ongoing",
    tags: ["Romance", "Adventure", "Myth"],
    description:
      "In a world where time is a currency, a young mage must unravel the secrets of eternal life to save her kingdom from a dark force.",
    longDescription:
      "As the mage delves deeper into the secrets of eternal life, she must navigate the treacherous world of time and the dark forces that threaten her kingdom.",
  },
  {
    id: 27,
    title: "Threads of Time",
    author: "Kara Ellis",
    cover: "/novels/rankings/romance_2.png",
    rating: 4.8,
    votes: 13030,
    chapters: 95,
    views: 130.3,
    genre: "Romance",
    status: "Ongoing",
    tags: ["Romance", "Adventure", "Myth"],
    description:
      "A former assassin turned detective must solve a series of murders that hint at a conspiracy within the city's elite.",
    longDescription:
      "As the detective delves deeper into the conspiracy, he must navigate the treacherous world of the city's elite and the dark secrets they hide.",
  },
  {
    id: 28,
    title: "Moonlit Sonata",
    author: "Iris Vayne",
    cover: "/novels/rankings/romance_3.png",
    rating: 4.8,
    votes: 14020,
    chapters: 110,
    views: 140.2,
    genre: "Romance",
    status: "Ongoing",
    tags: ["Romance", "Myth", "Adventure"],
    description:
      "A princess with the power to communicate with stars embarks on a journey to find her missing brother and uncover the truth about her kingdom's past.",
    longDescription:
      "As the princess delves deeper into the mysteries of her kingdom's past, she must navigate the treacherous world of court politics and the dark secrets that threaten her family.",
  },
  {
    id: 29,
    title: "The Painter’s Heart",
    author: "Ren Saito",
    cover: "/novels/rankings/romance_4.png",
    rating: 4.7,
    votes: 12010,
    chapters: 85,
    views: 120.1,
    genre: "Romance",
    status: "Ongoing",
    tags: ["Romance", "Action", "Adventure"],
    description:
      "A group of rebels fights against an oppressive empire in a world where magic and technology coexist.",
    longDescription:
      "As the rebels gain strength, they must navigate the treacherous world of magic and technology and the dark secrets that threaten their rebellion.",
  },
  {
    id: 30,
    title: "A Song for Tomorrow",
    author: "Clara Noveen",
    cover: "/novels/rankings/romance_5.png",
    rating: 4.6,
    votes: 10000,
    chapters: 70,
    views: 100.0,
    genre: "Romance",
    status: "Ongoing",
    tags: ["Romance", "Drama", "Myth"],
    description:
      "A young queen must navigate the treacherous waters of court politics and romance while trying to protect her kingdom from internal and external threats.",
    longDescription:
      "As the queen delves deeper into the mysteries of her kingdom, she must navigate the treacherous world of court politics and the dark secrets that threaten her rule.",
  },
  {
    id: 31,
    title: "The Clockmaker’s Secret",
    author: "Irene Weller",
    cover: "/novels/rankings/mystery_1.png",
    rating: 4.9,
    votes: 15050,
    chapters: 120,
    views: 150.5,
    genre: "Mystery",
    status: "Ongoing",
    tags: ["Mystery", "Adventure", "Myth"],
    description:
      "In a world where time is a currency, a young mage must unravel the secrets of eternal life to save her kingdom from a dark force.",
    longDescription:
      "As the mage delves deeper into the secrets of eternal life, she must navigate the treacherous world of time and the dark forces that threaten her kingdom.",
  },
  {
    id: 32,
    title: "Whispers in the Fog",
    author: "Dante Rowen",
    cover: "/novels/rankings/mystery_2.png",
    rating: 4.8,
    votes: 13030,
    chapters: 95,
    views: 130.3,
    genre: "Mystery",
    status: "Ongoing",
    tags: ["Mystery", "Adventure", "Myth"],
    description:
      "A former assassin turned detective must solve a series of murders that hint at a conspiracy within the city's elite.",
    longDescription:
      "As the detective delves deeper into the conspiracy, he must navigate the treacherous world of the city's elite and the dark secrets they hide.",
  },
  {
    id: 33,
    title: "Letters from the Abyss",
    author: "Celine Korr",
    cover: "/novels/rankings/mystery_3.png",
    rating: 4.8,
    votes: 14020,
    chapters: 110,
    views: 140.2,
    genre: "Mystery",
    status: "Ongoing",
    tags: ["Mystery", "Romance", "Adventure"],
    description:
      "A princess with the power to communicate with stars embarks on a journey to find her missing brother and uncover the truth about her kingdom's past.",
    longDescription:
      "As the princess delves deeper into the mysteries of her kingdom's past, she must navigate the treacherous world of court politics and the dark secrets that threaten her family.",
  },
  {
    id: 34,
    title: "Shadows of Hollow Street",
    author: "Mira Solen",
    cover: "/novels/rankings/mystery_4.png",
    rating: 4.7,
    votes: 12010,
    chapters: 85,
    views: 120.1,
    genre: "Mystery",
    status: "Ongoing",
    tags: ["Mystery", "Action", "Adventure"],
    description:
      "A group of rebels fights against an oppressive empire in a world where magic and technology coexist.",
    longDescription:
      "As the rebels gain strength, they must navigate the treacherous world of magic and technology and the dark secrets that threaten their rebellion.",
  },
  {
    id: 35,
    title: "The Mirror That Lied",
    author: "Lukas Thorne",
    cover: "/novels/rankings/mystery_5.png",
    rating: 4.6,
    votes: 10000,
    chapters: 70,
    views: 100.0,
    genre: "Mystery",
    status: "Ongoing",
    tags: ["Mystery", "Drama", "Romance"],
    description:
      "A young queen must navigate the treacherous waters of court politics and romance while trying to protect her kingdom from internal and external threats.",
    longDescription:
      "As the queen delves deeper into the mysteries of her kingdom, she must navigate the treacherous world of court politics and the dark secrets that threaten her rule.",
  },
];

export const library_novels: Novel[] = [
  {
    id: 1,
    title: "Moonlit Dreams",
    author: "Luna West",
    cover: "/soft-lavender-romantic-fantasy-book-cover.jpg",
    rating: 4.8,
    chapters: 156,
    views: 2.4,
    genre: "Fantasy",
    status: "Ongoing",
    progress: 50,
    tags: ["Fantasy", "Romance", "Magic"],
    description:
      "In a world where dreams hold magical power, a young woman discovers she can enter the dreams of others and must use this ability to save her kingdom from a dark force.",
  },
  {
    id: 2,
    title: "Ethereal Chronicles",
    author: "Aria Moon",
    cover: "/mystical-purple-epic-adventure-book-cover.jpg",
    rating: 4.6,
    chapters: 203,
    views: 3.1,
    progress: 30,
    genre: "Adventure",
    status: "Ongoing",
    tags: ["Epic", "Adventure", "Magic"],
    description:
      "A young adventurer embarks on a quest to find the legendary Ethereal Chronicles, a book said to hold the power to control the elements and save the world from destruction.",
  },
  {
    id: 3,
    title: "The Whispering Stars",
    author: "Alyssa K. Moran",
    chapters: 203,
    views: 3.1,
    progress: 90,
    description:
      "In a tranquil kingdom where the stars are believed to be silent watchers of fate, young astronomer Elara discovers she can hear their whispers — faint voices echoing through her telescope. As she learns to interpret their celestial language, the constellations reveal ominous prophecies of a coming darkness that threatens to swallow her world. Torn between loyalty to her king and the cosmic truths written in the heavens, Elara must choose whether to warn her people or risk being branded a heretic in a realm that no longer believes in magic.",
    rating: 4.8,
    genre: "Adventure",
    status: "Ongoing",
    tags: ["Epic", "Adventure", "Magic"],
    cover: "/novels/hero-section/novel_1.png",
  },
  {
    id: 4,
    title: "Chronicles of Emberfall",
    author: "Darius Vale",
    cover: "/novels/hero-section/novel_2.png",
    rating: 4.6,
    chapters: 95,
    progress: 80,
    views: 84.5,
    genre: "Fantasy",
    status: "Ongoing",
    tags: ["Fantasy", "Rebellion", "Magic"],
    description:
      "In a world where magic is forbidden, a group of rebels fights to restore the ancient magic and overthrow the tyrannical king.",
  },
  {
    id: 5,
    title: "The Silver Sonata",
    author: "Clara Noveen",
    cover: "/novels/hero-section/novel_3.png",
    rating: 4.9,
    chapters: 78,
    progress: 78,
    views: 99.2,
    genre: "Drama",
    status: "Completed",
    tags: ["Drama", "Romance", "Music"],
    description:
      "A young musician discovers a magical instrument that can bring her lost love back to life, but at a terrible cost.",
  },
];

export const novel_detail: Novel[] = [
  {
    id: 1,
    title: "Moonlit Dreams",
    author: "Luna West",
    cover: "/novels/hero-section/novel_1.png",
    rating: 4.8,
    votes: 2412,
    chapters: 156,
    views: 2.4,
    genre: "Fantasy",
    status: "Ongoing",
    tags: ["Magic", "Kingdom", "Dreams"],
    description:
      "In a world where dreams hold magical power, a young woman discovers she can enter the dreams of others and must use this ability to save her kingdom from a dark force.",
    longDescription:
      "As the lines between dreams and reality blur, Luna must face not only the monsters that haunt her sleep but also the dark truths that threaten to unravel her world.",
  },
  {
    id: 2,
    title: "Ethereal Chronicles",
    author: "Aria Moon",
    cover: "/mystical-purple-epic-adventure-book-cover.jpg",
    rating: 4.6,
    votes: 1985,
    chapters: 203,
    views: 1.8,
    genre: "Adventure",
    status: "Completed",
    tags: ["Magic", "Quest", "Myth"],
    description:
      "A grand tale of magic and destiny where a young mage must uncover the secrets of an ancient prophecy.",
  },
];

export const weeklyDATA: WeeklyData[] = [
  {
    id: 1,
    title: "Moonlit Dreams",
    cover: "/novels/hero-section/novel_1.png",
    genre: "Fantasy"
  },
  {
    id: 2,
    title: "Ethereal Chronicles",
    cover: "/novels/hero-section/novel_2.png",
    genre: "Adventure"
  },
  {
    id: 3,
    title: "The Whispering Stars",
    cover: "/novels/hero-section/novel_1.png",
    genre: "Adventure",
  },
  {
    id: 4,
    title: "Chronicles of Emberfall",
    cover: "/novels/hero-section/novel_2.png",
    genre: "Fantasy",
  },
  {
    id: 5,
    title: "The Silver Sonata",
    cover: "/novels/hero-section/novel_3.png",
    genre: "Drama",
  },
]