export const rankings = {
  "Top Overall": [
    {
      title: "Echoes of Eternity",
      author: "Luna Virelle",
      genre: "Fantasy",
      rating: 4.9,
      image: "/novels/rankings/overall_1.png",
    },
    {
      title: "Code of Shadows",
      author: "Rei Nakamura",
      genre: "Thriller",
      rating: 4.8,
      image: "/novels/rankings/overall_2.png",
    },
    {
      title: "The Whispering Stars",
      author: "Alyssa K. Moran",
      genre: "Fantasy",
      rating: 4.8,
      image: "/novels/rankings/overall_3.png",
    },
    {
      title: "Empire of Ashes",
      author: "Darius Vale",
      genre: "Action",
      rating: 4.7,
      image: "/novels/rankings/overall_4.png",
    },
    {
      title: "The Silent Crown",
      author: "Ren Saito",
      genre: "Drama",
      rating: 4.6,
      image: "/novels/rankings/overall_5.png",
    },
  ],
  "Top Fantasy": [
    {
      title: "Garden of Forgotten Dreams",
      author: "Ren Saito",
      genre: "Fantasy",
      rating: 4.9,
      image: "/novels/rankings/fantasy_1.png",
    },
    {
      title: "Chronicles of Emberfall",
      author: "Darius Vale",
      genre: "Fantasy",
      rating: 4.8,
      image: "/novels/rankings/fantasy_2.png",
    },
    {
      title: "The Last Eclipse",
      author: "Mira Solen",
      genre: "Fantasy",
      rating: 4.8,
      image: "/novels/rankings/fantasy_3.png",
    },
    {
      title: "The Silver Sonata",
      author: "Clara Noveen",
      genre: "Fantasy",
      rating: 4.7,
      image: "/novels/rankings/fantasy_4.png",
    },
    {
      title: "The Whispering Stars",
      author: "Alyssa K. Moran",
      genre: "Fantasy",
      rating: 4.7,
      image: "/novels/rankings/fantasy_5.png",
    },
  ],
  "Top Romance": [
    {
      title: "The Blossoming Veil",
      author: "Elara Mistral",
      genre: "Romance",
      rating: 4.9,
      image: "/novels/rankings/romance_1.png",
    },
    {
      title: "Threads of Time",
      author: "Kara Ellis",
      genre: "Romance",
      rating: 4.8,
      image: "/novels/rankings/romance_2.png",
    },
    {
      title: "Moonlit Sonata",
      author: "Iris Vayne",
      genre: "Romance",
      rating: 4.8,
      image: "/novels/rankings/romance_3.png",
    },
    {
      title: "The Painter’s Heart",
      author: "Ren Saito",
      genre: "Romance",
      rating: 4.7,
      image: "/novels/rankings/romance_4.png",
    },
    {
      title: "A Song for Tomorrow",
      author: "Clara Noveen",
      genre: "Romance",
      rating: 4.6,
      image: "/novels/rankings/romance_5.png",
    },
  ],
  "Top Mystery": [
    {
      title: "The Clockmaker’s Secret",
      author: "Irene Weller",
      genre: "Mystery",
      rating: 4.9,
      image: "/novels/rankings/mystery_1.png",
    },
    {
      title: "Whispers in the Fog",
      author: "Dante Rowen",
      genre: "Mystery",
      rating: 4.8,
      image: "/novels/rankings/mystery_2.png",
    },
    {
      title: "Letters from the Abyss",
      author: "Celine Korr",
      genre: "Mystery",
      rating: 4.8,
      image: "/novels/rankings/mystery_3.png",
    },
    {
      title: "Shadows of Hollow Street",
      author: "Mira Solen",
      genre: "Mystery",
      rating: 4.7,
      image: "/novels/rankings/mystery_4.png",
    },
    {
      title: "The Mirror That Lied",
      author: "Lukas Thorne",
      genre: "Mystery",
      rating: 4.6,
      image: "/novels/rankings/mystery_5.png",
    },
  ],
};